### ISSUE TITLE
bias_sigma initialization in noisy net

### ISSUE THREAD

**Issue by kentropy** [Curt-Park/rainbow-is-all-you-need#48]
According to Sec. 3.2 in the paper "Noisy Networks for Exploration", sigmas are initialized to a constant `sigma / sort(p)`.
However, in this implementation, `self.bias_sigma.data.fill_(self.std_init / math.sqrt(self.out_features))` is realized. Is this a typo?

**Comment by Curt-Park** [comment]
That is intended because the number of bias is equal to `out_features`.
At the moment I worked on this repository, there was no official NoisyNet implementation, so people made it in different ways; some people used `out_features`, or some people used `in_features` for the initial value of bias_sigma.

However, DeepMind published their [Rainbow implementation](https://github.com/deepmind/dqn_zoo) in 2020, and they state the initial bias sigma as `self.std_init / math.sqrt(in_features)` (See the [code](https://github.com/deepmind/dqn_zoo/blob/master/dqn_zoo/networks.py#L134)). 

I am considering to change the initialization logic like DeepMind's NoisyNet.

**Comment by Curt-Park** [comment]
I will close this issue. If you have more things to discuss, please reopen.
